# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - release_automation

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'f5networks/k8s-bigip-ctlr-devel'
  dockerRepo: 'f5networks/k8s-bigip-ctlr'
  redhatRepo: 'f5networks/k8s-bigip-ctlr'
  quayConnection: 'quay-bot'
  dockerConnection: 'docker-bot'
  redhatConnection: 'redhat-bot'
  redhatPush: 'redhat-push'
  # scan.connect.redhat.com
steps:
  - task: Docker@2
    displayName: Login to redhat registry
    inputs:
      command: login
      containerRegistry: $(redhatConnection)
  - task: Docker@2
    displayName: Login to quay registry
    inputs:
      command: login
      containerRegistry: $(quayConnection)
  - task: Docker@2
    displayName: Login to docker registry
    inputs:
      command: login
      containerRegistry: $(dockerConnection)
  - task: CmdLine@2
    displayName: Check documentation
    inputs:
      script: 'make docs'
  - task: Docker@2
    displayName: Build from Red Hat Universal Base Image
    inputs:
      command: build
      containerRegistry: $(quayConnection)
      repository: $(imageName)
      Dockerfile: build-tools/Dockerfile-int
      buildContext: .
      tags: |
        $(Build.SourceVersion)
        latest
      arguments: "--build-arg BUILD_INFO=azure-$(Build.BuildId)-$(Build.SourceVersion) --build-arg BUILD_VERSION=$(BUILD_VERSION) --build-arg RUN_TESTS=$(RUN_TESTS)"
  - task: Docker@2
    displayName: Push image to quay.io
    inputs:
      command: push
      containerRegistry: $(quayConnection)
      repository: $(imageName)
      tags: latest
  - task: Docker@2
    displayName: Push image to docker registry
    inputs:
      command: push
      containerRegistry: $(dockerConnection)
      repository: $(dockerRepo)
      tags: |
        $(BUILD_VERSION)
        latest
  - task: Docker@2
    displayName: Push image to redhat registry
    inputs:
      command: push
      containerRegistry: $(redhatConnection)
      repository: $(dockerRepo)
      tags: |
        $(BUILD_VERSION)
        latest

